package org.rubenrr.walkeitor.element.consumable;

import org.rubenrr.walkeitor.config.element.ConsumableConfig;

/**
 * Product generated by the OIL_MINE
 *
 * User: Ruben Rubio Rey
 * Date: 30/04/13
 * Time: 8:11 PM
 */
public class CrudeOil extends Consumable {

    private ConsumableConfig consumableConfig = ConsumableConfig.CRUDE_OIL;

    public CrudeOil() {
        this(0f);
    }
    public CrudeOil(float value) {
        super(ConsumableConfig.CRUDE_OIL, value);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof CrudeOil)) return false;

        CrudeOil crudeOil = (CrudeOil) o;

        if (consumableConfig != crudeOil.consumableConfig) return false;

        return true;
    }

    @Override
    public int hashCode() {
        return consumableConfig != null ? consumableConfig.hashCode() : 0;
    }

}
