package org.rubenrr.walkeitor.element.consumable;

/**
 * Product generated by the OIL_MINE
 *
 * User: Ruben Rubio Rey
 * Date: 30/04/13
 * Time: 8:11 PM
 */
public class CrudeOil implements Consumable {
    private int value = 0;

    @Override
    public int getAmount() {
        return this.value;
    }
}
