package org.rubenrr.walkeitor.element.consumable;

/**
 * Fuel is the product generated by the refinery after process the Crude Oil
 *
 * User: Ruben Rubio Rey
 * Date: 30/04/13
 * Time: 8:12 PM
 */
public class Fuel implements Consumable {

    private int value = 0;

    @Override
    public int getAmount() {
        return this.value;  //To change body of implemented methods use File | Settings | File Templates.
    }
}
